### ISSUE TITLE
Upvalue reassigned

### ISSUE THREAD

**Issue by SquidDev** [SquidDev/luaj.luajc#4]
From SquidDev-CC/Studio#14 and #1 

We are getting generation errors with a very edge case piece of code:

``` lua
local upvalue

local function closure()
    return upvalue
end

while true do
    if "const" ~= "const" then
        upvalue = "const"
    else
        for loop_num = "const", "const" do
            for loop_iter in func() do
                func(loop_num + loop_iter)
            end
        end
    end
end
```

The trouble is at the end of the for loop (line 12: `for loop_iter in func()`). As the upvalue is reassigned within a branch statement there seems to be an issue that the upvalue is created and stored as an upvalue straight away, and so the upvalue slot is empty.

It seems it wants to convert an upvalue despite one has already been converted.

Something is breaking in [the logic here](https://github.com/SquidDev/luaj.luajc/blob/6eb312525c8737057650c157230a980b522d29b0/src/main/java/org/squiddev/luaj/luajc/UpvalueInfo.java#L55-L138) to do with loops.

**Comment by viluon** [comment]
Congrats :clap: :+1: :+1:

**Comment by SquidDev** [comment]
Yay! A 1 line change after 10 months!

**Comment by viluon** [comment]
yeah, those are the worst bugs :stuck_out_tongue:

**Comment by Creator** [comment]
WOW :clap:
